---
title: "Foundations for Machine Learning"
description: | 
  Notes for the morning session for day 2 of NAAMII's Winter School on AI.
site: distill::distill_website
listing: posts
---


## Learning Outcomes

Notebooks [[1](https://colab.research.google.com/drive/10jGSLch_g7G72L41rjnswx69PXneeT3w), [2](https://colab.research.google.com/drive/1uJPeyBMRN3vqCoALCvik6X4ccGdpc3zS), [3](https://colab.research.google.com/drive/1C--MSMalpnjh4R5WkgL70J4IIpKlg6U0)]

1. Given a problem description, determine features that may be relevant, including those directly present in the raw data and those that must be constructed.
2. Given a problem description, determine an appropriate response variable.
3. Design a model evaluation scheme for a specific problem / model context, keeping in mind the dangers of overfitting and the bias-variance trade-off.
4. Given a covariate / response pair, use visualization and summary statistics to identify preprocessing or transformation methods that may improve downstream model performance.
5. Discuss the relative merits of linear, sparse, and tree-based methods in a particular problem setting, and prepare code that implements them appropriately.
6. Use model summaries and data visualization to summarize the important features in a model and note areas for potential improvement.

## Exercises

Exercises from this session are available [here](https://docs.google.com/document/d/1EbjbHa6UW392LbIl7HVHEFfc9hYjUZnsJ8CPm4DZfd4/edit?usp=sharing)